# conda env create -f environment.yml && conda activate phaseretrieval
name: phaseretrieval
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - -r requirements.txt
      - -e .
